### ISSUE TITLE
Result visualization and error calculation 

### ISSUE THREAD

**Issue by YuejiangLIU** [vvanirudh/srnn-pytorch#2]
Thanks for the code. I have two questions regarding the result evaluations: 
- After running your train.py and sample.py, I tried to visualize the trajectories predicted by the model, and found most of them unreasonable. I suspect if I did anything wrong. Do you see accurate predictions from your model?
- Is there a bug for the counter in get_mean_error? From my understanding, the counter should be reset to zero at the beginning of each tstep in get_mean_error. Otherwise, the mean error might have been dramatically under-estimated?

**Comment by avijit9** [comment]
Yes. In the get_mean_error function, the counter should be reset to zero after every timestep as per my understanding. @vvanirudh  can you correct us?

**Comment by vvanirudh** [comment]
You guys are right. The counter should be reset to zero after each time-step. That is a bug in the code.

**Comment by avijit9** [comment]
@vvanirudh  even after the correction, the values of FDE and ADE I am unable to reproduce the results. Can you please check whether you are able to reproduce the results?

**Comment by vvanirudh** [comment]
I will try running the model again and will let you know

**Comment by avijit9** [comment]
Thanks a lot. If you can also push the code for conversion of coordinates from pixel space to world coordinate space, I can also run the models again. I have given the code I am using for this purpose in the other issue. My suspicion is that I am making some mistake in that function. But I double checked it. Could not find any problem :|

**Comment by vvanirudh** [comment]
Yeah I took a look at that. I did my conversion in matlab script using the pixel space errors. Let me see if I can pull that script off the server
